name: "Build And Test"
on: ["push", "pull_request"]

jobs:
    RunTestsOnMacOS:
      runs-on: "macos-latest"
      steps:
        - uses: "actions/checkout@v3"
        - name: "Add Dependencies"
          run: "brew install gcc"
        - name: "Build"
          run: |
            cd example
            make all
        - name: "Run Example"
          run: |
            sudo ./example/ping_example 127.0.0.1
            sudo ./example/ping_example 0:0:0:0:0:0:0:1
          
    RunTestsOnLinux:
      runs-on: "ubuntu-latest"
      steps:
        - uses: "actions/checkout@v3"
        - name: "Add Dependencies"
          run: "sudo apt update -q && sudo apt install -yq g++"
        - name: "Build"
          run: |
            cd example
            make all
        - name: "Run Example"
          run: |
            sudo ./example/ping_example 127.0.0.1
            # sudo ./example/ping_example 0:0:0:0:0:0:0:1
    RunTestsOnWindows:
      runs-on: "windows-latest"
      steps:
        - uses: "actions/checkout@v3"
        - name: "Set up MinGW"    
          uses: "egor-tensin/setup-mingw@v2"
          with:
            platform: "x64"
        - name: "Build"
          run: |
            cd example
            g++ -std=c++11 -Wall -I../ -lws2_32 -lWldap32 -lCrypt32 -O3 -o ping_example ping.cpp
        - name: "Run Example"
          run: |
            sudo ./example/ping_example 127.0.0.1
            # sudo ./example/ping_example 0:0:0:0:0:0:0:1
        